### ISSUE TITLE
Initial release todo list

### ISSUE THREAD

**Issue by overcat** [overcat/c-stellar-base#1]
## modules
- [x] xdr files
- [x] strkey
- [x] keypair
- [x] muxed account
- [x] memo
- [x] signer key
- [x] signer
- [x] asset
- [x] liquidity pool asset
- [x] transaction
- [x] transaction_envelope
- [x] fee_bump_transaction
- [x] fee_bump_transaction_envelope
## operations
- [x] CREATE_ACCOUNT
- [x] PAYMENT
- [x] PATH_PAYMENT_STRICT_RECEIVE
- [x] MANAGE_SELL_OFFER
- [x] CREATE_PASSIVE_SELL_OFFER
- [x] SET_OPTIONS
- [x] CHANGE_TRUST
- [x] ALLOW_TRUST
- [x] ACCOUNT_MERGE
- [x] INFLATION
- [x] MANAGE_DATA
- [x] BUMP_SEQUENCE
- [x] MANAGE_BUY_OFFER
- [x] PATH_PAYMENT_STRICT_SEND
- [x] CREATE_CLAIMABLE_BALANCE
- [x] CLAIM_CLAIMABLE_BALANCE
- [x] BEGIN_SPONSORING_FUTURE_RESERVES
- [x] END_SPONSORING_FUTURE_RESERVES
- [x] REVOKE_SPONSORSHIP
- [x] CLAWBACK
- [x] CLAWBACK_CLAIMABLE_BALANCE
- [x] SET_TRUST_LINE_FLAGS
- [x] LIQUIDITY_POOL_DEPOSIT
- [x] LIQUIDITY_POOL_WITHDRAW
## Others
- [ ] code clean up and refactor
